apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-first
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet-first
  template:
    metadata:
      labels:
        app: dotnet-first
    spec:
      containers:
        - name: dotnet
          image: nlrcmani/dotnet-sample-1
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-first
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: dotnet-first