apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-first
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotnet-first
  template:
    metadata:
      labels:
        app: dotnet-first
    spec:
      containers:
        - name: dotnet
          image: nlrcmani/dotnet-sample-1
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-first
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: dotnet-first